[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nupstup"
description = "The Nupstup -- optimization easy to use"
readme = "README.rst"
requires-python = ">=3.7"
license = { text = "MIT" }
keywords = ["optimization", "gurobipy", "pandas"]
authors = [
    { name = "Simon Bowly", email = "bowly@gurobi.com" },
    { name = "Robert Luce", email = "luce@gurobi.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "feather-format",
    "gurobipy",
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "networkx",
    "sklearn",
]
dynamic = ["version"]

[tool.hatch.version]
path = "src/nupstup/__init__.py"
