# Run the doctests against python 3.8 + gurobipy 10.

name: Doc tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
        gurobipy: ["10.0.1"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install gurobipy==${{ matrix.gurobipy }}
          python -m pip install .
          python -m pip install -rdocs/requirements.txt
      - name: Run doctests
        run: |
          cd docs
          sphinx-build -M doctest source build
